# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ab30c66f0fecfb4e90a1f70e23d295057261abc847cce445b7fcb57d22cee34f0f7bde71b1715dcfb5bb595658e5c7edf1ed600d327ba2794dec61b52ea2b28

test:
  secret_key_base: 6145a0419e501c5ad42b29f8c39421554a8c41f5c587aa4638817a1436fd753a11779b119ca3b0f340ac5065746fdb152911a12b92e045a0b38d45e15d55a242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
